### PR TITLE
Revert "Fix broken tests (#85)" because the PR actually breaks tests

### PR DESCRIPTION
**Pull request by Vinai**
This reverts commit dde4eb0097974e15a82f680260e42a57034701a6.

Closes issue #87

### CODE REVIEW

**Comment by zephanhazell** [comment]
@Vinai your comments make sense. I am assuming that you were testing on a local setup? I was testing against https://hyva-demo.elgentos.io/ since I don't have a local Hyva setup (We are still on Luma for now...) and this suite was set to run again that site.

I had made the (perhaps wrong) assumption that https://hyva-demo.elgentos.io/ was Hyva standard setup running Magento 2.4 with Hyva 1.1.17. Perhaps there has actually been a change to the site that caused the tests to break and instead of changing the tests the site needs to be updated? @peterjaap has there been any recent changes to https://hyva-demo.elgentos.io/. If changes have been made then yeah we should revert my PR and update the site.

I did confirm again that all tests still pass in CI with my version. (See screenshot below) I ran this against my own Cypress Project since I don't think I have permissions to run in this repo.

image

**Comment by Vinai** [comment]
@zephanhazell I am running the tests against a fresh M2 + Hyvä install in CI in addition to a local installation.

It would indeed be interesting to know in what way https://hyva-demo.elgentos.io/ is different.

**Comment by peterjaap** [comment]
@Vinai I put the version numbers on the homepage;

> This shop runs on:
> - Magento 2.4.5 with sample data
> - Hyvä theme 1.1.17 & Hyvä React Checkout 1.1.1
> - ElasticSuite 2.10.11 + Hyvä compatibility module 1.1.1
> - [Hypernode Falcon S](https://www.hypernode.com/magento-hosting/) (PHP 8.1 / MySQL 8.0 / ElasticSearch 7.6 / Varnish 6)

So maybe it has something to do with Elasticsuite?

It's still on my todo list to spin up a vanilla Magento + Hyva instance inside Github Actions but haven't come round to it yet.

**Comment by Vinai** [comment]
I agree Elastic is the likely culprit.

**Comment by peterjaap** [comment]
I am closing this issue because as far as I can see, nothing is broken at the moment. Here's the latest run result; https://dashboard.cypress.io/projects/8vuidn/runs/e0a3cf9c-9653-4b03-97cc-04178dd6adb8/test-results/044b4dba-9ee4-43ec-8db0-6fcf12c95df5

**Pull request closed without merging**
