### PR TITLE
feat: create coupon code via Magento REST api

### PR DESCRIPTION
**Pull request by kolaente**
This PR adds a method to the REST API helper to create random coupon codes on the fly during a test.

Use it like this:

```js
it('Can add a coupon to the cart', () => {
    Magento2RestApi.createRandomCouponCode()
        .then(coupon => {
            Cart.addCouponCode(coupon)
            cy.get(cartLuma.cartSummaryTable)
                .should('include.text', 'Discount')
                .should('be.visible')
        })
})
```

I'll do a follow-up PR to add this to the tests.

### CODE REVIEW

**Comment by peterjaap** [comment]
Love it! But why the insanely high timeout of 100000?

**Comment by kolaente** [comment]
Good question! I copied the `cy.request` statement from `createCustomerAccount` and it was already in there.

What would be a better timeout? Might make sense to set this to the same value for all requests in the file? (`logCustomerIn` has a timeout of 50000, the other ones have 100000)

**Comment by peterjaap** [comment]
@kolaente I think you can just remove it, so it will use the default timeout set in Cypress (5000 by default). Unless there's a specific (and valid) reason to raise it, just leave it at the default.

**Comment by kolaente** [comment]
Done!

**Comment by peterjaap** [comment]
I still see timeouts in the commit?

**Comment by kolaente** [comment]
Looks like I forgot one, whoops. Should I also remove the ones which were already present in the other tests?

**Comment by peterjaap** [comment]
I still see 3;

image

image

**Comment by kolaente** [comment]
Gotcha, I've removed all of them.

**Comment by peterjaap** [comment]
I realized now some of those weren't yours, haha. Thanks! :)

**Pull request merged**
